# Generated by Django 4.2.4 on 2023-09-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='popularity_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
