# Generated by Django 4.2.4 on 2023-09-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
