# Generated by Django 4.2.4 on 2023-09-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='newPage',
        ),
    ]
