# Generated by Django 4.2.4 on 2023-09-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_page_newpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newPage',
        ),
    ]
